apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharedlibrary-claim
  namespace: pipelines-runs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi