apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: ci-security
  namespace: pipelines-runs
spec:
  inputs:
    resources:
      - name: source
        type: git
  
  steps:
    - name: horusec-security
      workingDir: /workspace/source
      image: docker
      script: |
        #!/usr/bin/env sh
        ls -l
        docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src/horusec horuszup/horusec-cli:latest horusec start -p /src/horusec -P $(pwd)
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
    - name: trivy
      workingDir: /workspace/source
      image: docker
      script: |
        #!/usr/bin/env sh
         docker build -t appbuid .
         docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.20.2 appbuid:latest
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
  sidecars:
    - image: docker:18.05-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}