apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: basic-example-p3-python
spec:
  params:
    - name: runtime
      type: string
      default: python
  tasks:
    - name: p3-task-1
      taskRef:
        name: p3-task-1
      params:
        - name: runtime
          value: "$(params.runtime)"        
 

