apiVersion: v1
kind: Pod
metadata:
  name: pod-sharedlibrary
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: sharedlibrary
      mountPath: /sharedlibrary
  volumes:
  - name: sharedlibrary
    persistentVolumeClaim:
      claimName: sharedlibrary-claim
