apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-sidecars-docker
spec:
  steps:
    - image: docker
      name: client
      script: |
        #!/usr/bin/env sh
        cat > Dockerfile << EOF
        FROM alpine:latest
        RUN apt-get update
        ENTRYPOINT ["echo", "hello"]
        EOF
        cat Dockerfile 
        docker build -t hello . 
        docker images
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}