apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  # The name of the task
  name: build-test-app-task
spec:
  resources:
    inputs:
    - name: git
      type: git
        # The input resource(s) of the task, such as a GitHub repository
  volumes:
    # Mount the docker socket from the node for building images
    # See the tutorial for more information
    - name: docker-socket
      hostPath:
        type: Socket
        path: /var/run/docker.sock
  steps:
    # Each step of the task
  - name: pytest
    image: python
    command:
    - /bin/bash
    - -c
    args:
    - cd /workspace/git/ && ls -l  && pip3 install -r requirements.txt   
  - name: build
    image: quay.io/buildah/stable:v1.17.0
    script: |
       buildah --storage-driver=overlay bud \
          --no-cache -f /workspace/git/Dockerfile -t app .
  # Volumes mounted to support Katacoda single-node K8S environment
  volumes:
  - name: dsocket
    persistentVolumeClaim:
      claimName: dsocket-vol-claim
  - name: dlib
    persistentVolumeClaim:
      claimName: dlib-vol-claim