apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app-task
spec:
  resources:
    inputs:
      # The input resource(s) of the task, such as an image
  steps:
  steps:
  # Deploy the image
  - name: deploy
    image: lachlanevenson/k8s-kubectl
    args:
      - run
      - myapp
      - --image=app
  # Expose the image for external acceess
  - name: expose
    image: lachlanevenson/k8s-kubectl
    args:
    - expose
    - pod
    - myapp
    - --port=80
    - --target-port=8080
    - --name=mysvc
    - --type="NodePort"  
    # Each step of the task
