apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: taskrun-cd
  namespace: pipelines-runs
spec:
  inputs:
    resources:
        - name: source
          resourceRef:
             name: source
    params:
      - name: IMAGE
        value: "clodonil/apphello:1"        
             
  taskRef:
     name: deploy