apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: giropops-ci
spec:
  inputs:
    resources:
      - name: giropops
        type: git
    params:
      - name: OUTPUT
        description: The image tag which will be built
        default: clodonil/typescript-ex:latest
  steps:
    - name: npm-install
      image: node
      command: 
        - /bin/sh
        - -c
      args:
        - npm install
      workingdir: /workspace/giropops
    - name: test
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run test
      workingDir: /workspace/giropops
    - name: build
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run build
      workingDir: /workspace/giropops
    - name: build-image
      image: quay.io/buildah/upstream:latest   
      securityContext:
        runAsUser: 0
        privileged: true
      workingDir: /workspace/giropops
      script: |
        buildah bud --tag=$(inputs.params.OUTPUT) .
      volumeMounts:
        - name: containers-storage
          mountPath: /var/lib/containers
    - name: push
      image: quay.io/buildah/upstream:latest
      securityContext:
        runAsUser: 0
        privileged: true
      script: |
        buildah push $(inputs.params.OUTPUT)
      volumeMounts:
         - name: containers-storage
           mountPath: /var/lib/containers
  volumes:
    - name: containers-storage
      emptyDir: {}              